### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by theroundball** [fmalina/PDFtranscript#1]
I am trying to implement your script on my converted html pages, but I don't understand how to. 

Do I simply place transcript.py in the directory with the converted html and run 'python transcript.py'? 

Also when I run it I get errors telling me:

File "transcript.py", line 25, in <module>
    from ttf import pua_content, recover_text
  File "/Users/hartley9/Desktop/transcript-master/ttf.py", line 47
SyntaxError: Non-ASCII character '\xe2' in file /Users/hartley9/Desktop/transcript-master/ttf.py on line 47, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

I have followed many tutorials explaining that I need to install lxml.html, I've installed it but it still doesn't work. 

Sorry I realize these aren't very constructive issues, and maybe you don't find them worth helping me with, but any help is very much appreciated!

**Comment by fmalina** [comment]
## Install

Get Python 3 installed along with latest pdf2htmlEX.
e.g. with Homebrew:

```
brew install python3 pdf2htmlEX
```

Install lxml under python3 `pip3 install lxml` or just run the following and get freetype-py too.

```
pip3 install -r requirements.txt
```

## Configure

Configure your project path in config.py most importantly the DATA_DIR on top. This can be any folder let's say `/Users/hartley9/Desktop/transcript-data`. Go ahead create it.

Your DATA_DIR should end up containing 3 folders: PDF, HTML and HTM if you otherwise stick with default configuration. Create a 'PDF' folder and drop your PDFs there.
- PDF is a folder where your PDFs are.
- HTML is where pdf2htmlEX output (non-semantic HTML) ends up after running `./pdf2html.py`. `./pdf2html.py` just runs pdf2htmlEX with suitable options.
- HTM is the final destination where semantic HTML gets born after running `./transcript.py`.

## Run

`./pdf2html.py`
`./transcript.py`

When you change configuration within `./transcript.py` or tweak some code. You only need to run `./transcript.py`

**Comment by fmalina** [comment]
Instructions are now part of the README and I added more comments to the config file.
I hope that helps. I am closing the issue now, feel free to reopen if you need more help to get Transcript running or file another issue.

**Comment by theroundball** [comment]
Thank you, I was able to get it up and running! 

It looks like I will have to play with the settings to get it to work with the pages I'm dealing with :)

**Comment by fmalina** [comment]
Ok, feel free to link here or email me the PDF in question if you can. I am putting together some test case PDFs and on these I want transcript.py to give reasonable output out of the box with just the default settings.

**Comment by theroundball** [comment]
This is an example pdf from the library we are trying to convert to HTML
SEO compatible pages.

PDF2html converter converts them visually perfectly, but we are finding
that it is not seo compatible.

Are you able to convert them so that they maintain them visually as well as
produce crawl-able html.

Thank you!

Garrett

**Comment by fmalina** [comment]
There is a setting `STRIP_CSS`, which is set to 1/True by default allowing users to plug in their own CSS. Leaving inline CSS in the document is not detrimental to SEO, but not suitable for type setting and further conversion to formats such as ePub etc. STRIP_CSS = 0 could be a working poor man's solution, but could also make a mess depending on the document and certainly wouldn't be responsive.

If your library or collection of documents is homogenous when it comes to design and layout patterns, then it is quite possible to arrive to good responsive design as well as findability. Maintaining PDF visually 100% is not suitable for presenting publications on the web. Mobile friendliness is an important SEO factor too.
