### ISSUE TITLE
Running pdf2html.py

### ISSUE THREAD

**Issue by Balmung421** [fmalina/PDFtranscript#3]
Hello,

Wanted to thank you for creating this, for I have a similar need where I need to batch convert pdfs to html. Having never worked in python before, I have followed your steps in getting this all set up. When I run `./pdf2html.py`however, my terminal screen only pops up with `[ ]`. 

I am confident this is user error, and will keep tinkering around, but any suggestions would be very appreciated.

**Comment by AnhellO** [comment]
@Balmung421, did you change the `DATA_DIR` path to your project's path on the `config.py`?. Also, on your project's root folder, you should create a PDF folder (you can create the HTML and HTM directories as well) where you will put all the PDF's you want to convert (beware with the [names](https://github.com/fmalina/transcript/blob/master/pdf2html.py#L26) of your PDFs). It popped up an empty list because no PDF was found/converted

**Comment by AnhellO** [comment]
@fmalina I have a doubt with the `FULL_FONTS_PATH`, I'm not pretty sure what path to use there, could you help me with this?, also, is there anything else needed (like downloading certain fonts for example) for the ttf.py script? I ask this because the description about the `FULL_FONTS_PATH` on the `config.py` talks about some original fonts: `# used by ttf.py to access full original fonts to compare with the broken ones`

**Comment by fmalina** [comment]
Use a path where you store full version of the true type fonts (TTF) that you think are used in your PDFs (complete original .ttf files, e.g. Arial.ttf).
If you put too many fonts there, this will negatively affect performance, so choose your pick.
This will allow ttf.py to compare glyphs (vector letter shapes) of the full original font with the shapes of the deficient embedded font from the PDF file deducing the actual symbol represented by given shape.
